audit_header: false
title: San Joaquin Valley/Bay Area Real Estate Video Blog with Patricia Soltero Gillet
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Patricia Soltero Gillet
  title:
  license_number:
  about_markdown: |
    It is a passion of mine and a pleasure to proudly serve my community to enable everyone I meet to fulfill their dreams in Real Estate, whether it is buying or selling your first home, investing in your future goals or supplying all of your financial needs. For over 20 years, I have been inspired and committed to improving myself through education, striving to make your real estate experience the most professional rewarding and exciting as possible. I am proud and honored to serve a referral based business and I believe that success is only present when our service to others is genuinely and passionately delivered with professionalism, integrity, and honesty. I proudly serve these qualities with hopes of building more lifelong relationships and outstanding achievements for everyone.
  market: San Joaquin Valley/Bay Area
  brand: Catalyst Real Estate
  brokerage: Hablo Español
  address: 1810 Pacific Ave, Stockton, CA 95204
  phone: 209-483-6220
  phone_type:
  phone2:
  phone2_type:
  email: patriciasgillet@gmail.com
  url: http://HomesByPatricia.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://homesbypatricia.com/MarketAnalysis
  second_CTA_text: Home Search
  second_CTA_URL: http://homesbypatricia.com/lss

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://homesbypatricia.com/MarketAnalysis

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://homesbypatricia.com/lss

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/homesbypatriciasolterogillet
  linkedin_url: https://www.linkedin.com/in/patricia-gillet-57169b8a/
  gplus_url: https://plus.google.com/104713986248891576095
  youtube_url: https://www.youtube.com/channel/UCcFJqBLqBUcRN8zUdYSDcvA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#36c034'
  theme_color: '#005375'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
